const INVOICE_STATUS = {
  DRAFT: 'DRAFT',
  PAID: 'PAID',
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
};

module.exports = {
  INVOICE_STATUS,
  HTTP_STATUS,
};
